Repository react-ui-org/react-ui, pull requests merged in 2020-12, with the labels that each got.

#200 Validate transitions and honor user's `prefers-reduced-motion` settings (#137)
  src/lib/components/ui/Button/_tools.scss
  src/lib/components/ui/Table/Table.scss
  src/lib/styles/tools/_transition.scss
  src/lib/styles/tools/forms/_foundation.scss
Labels: feature

#202 Automatically assign PR to its author upon creation
  .github/workflows/pr-labeler.yml
  .github/workflows/pull-request-meta.yml
Labels: maintenance

#201 Update dependencies (#196)
  package-lock.json
  package.json
  src/lib/components/ui/Button/Button.jsx
  src/lib/components/ui/CheckboxField/CheckboxField.jsx
  src/lib/components/ui/SelectField/SelectField.jsx
  src/lib/components/ui/TextArea/TextArea.jsx
  src/lib/components/ui/TextField/TextField.jsx
  src/lib/components/ui/Toggle/Toggle.jsx
  webpack.config.js
Labels: feature

#203 Require Node 14 for development and CI as it's current LTS
  .github/workflows/release-management.yml
  .github/workflows/test.yml
  package.json
Labels: maintenance

#204 Bump version to v0.36.0
  package-lock.json
  package.json
Labels: skip changelog

#205 Disallow update of release name in attempt to fix unprefixed Git tags being created on release
  .github/workflows/release-management.yml
Labels: maintenance

#206 Fix `Grid` prop types and cover it with better tests
  src/lib/components/layout/Grid/Grid.jsx
  src/lib/components/layout/Grid/GridSpan.jsx
  src/lib/components/layout/Grid/__tests__/Grid.test.jsx
  src/lib/components/layout/Grid/__tests__/GridSpan.test.jsx
  src/lib/components/layout/Grid/__tests__/__snapshots__/Grid.test.jsx.snap
  src/lib/components/layout/Grid/__tests__/__snapshots__/GridSpan.test.jsx.snap
Labels: bugfix

#207 Bump version to v0.36.1
  package-lock.json
  package.json
Labels: skip changelog

#211 Rename default `Badge` and `Button` priority to more descriptive `filled` (#209)
  src/lib/components/ui/Badge/Badge.jsx
  src/lib/components/ui/Badge/README.mdx
  src/lib/components/ui/Badge/__tests__/Badge.test.jsx
  src/lib/components/ui/Badge/__tests__/__snapshots__/Badge.test.jsx.snap
  src/lib/components/ui/Button/Button.jsx
  src/lib/components/ui/Button/README.mdx
  src/lib/components/ui/Button/__tests__/__snapshots__/Button.test.jsx.snap
  src/lib/components/ui/Button/_priorities.scss
  src/lib/components/ui/Button/_theme.scss
  src/lib/components/ui/ButtonGroup/ButtonGroup.jsx
  src/lib/components/ui/ButtonGroup/README.mdx
  src/lib/components/ui/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
  src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/lib/theme.scss
Labels: BC
