Repository react-ui-org/react-ui, pull requests merged in 2020-05, with the labels that each got.

#63 Update dependencies (#62)
  package-lock.json
  package.json
Labels: dependencies

#69 Configure GitHub test workflow
  .github/workflows/test.yml
  .npmignore
  Jenkinsfile
  build.sh
  docker-compose.yml
  docker/Node/Dockerfile
  docker/Node/init-container.sh
  package-lock.json
  package.json
Labels: maintenance

#74 Add text color utility classes (#64)
  src/demo/pages/DemoContainer.jsx
  src/demo/pages/navigation.js
  src/lib/styles/settings/_utilities.scss
Labels: feature

#76 Block merge of fixup commits (#75)
  .github/workflows/git.yml
  .github/workflows/test.yml
Labels: maintenance
