Repository react-ui-org/react-ui, pull requests merged in 2020-10, with the labels that each got.

#158 Drop `Login` compositions (#157)
  src/demo/pages/DemoContainer.jsx
  src/demo/pages/navigation.js
  src/lib/components/screens/Login/ForgotPassword.jsx
  src/lib/components/screens/Login/ForgotPassword.scss
  src/lib/components/screens/Login/Login.jsx
  src/lib/components/screens/Login/Login.scss
  src/lib/components/screens/Login/NewPassword.jsx
  src/lib/components/screens/Login/NewPassword.scss
  src/lib/components/screens/Login/__tests__/ForgotPassword.test.jsx
  src/lib/components/screens/Login/__tests__/Login.test.jsx
  src/lib/components/screens/Login/__tests__/NewPassword.test.jsx
  src/lib/components/screens/Login/__tests__/__snapshots__/ForgotPassword.test.jsx.snap
  src/lib/components/screens/Login/__tests__/__snapshots__/Login.test.jsx.snap
  src/lib/components/screens/Login/__tests__/__snapshots__/NewPassword.test.jsx.snap
  src/lib/components/screens/Login/_mixins.scss
  src/lib/components/screens/Login/index.js
  src/lib/index.js
Labels: BC

#161 Merge CSS helpers and utilities into single SCSS endpoint to make their use easier
  README.md
  src/demo/pages/DemoContainer.jsx
  src/lib/foundation.scss
  src/lib/helpers.scss
  src/lib/styles/_utilities.scss
  src/lib/styles/helpers/_animation.scss
Labels: BC

#160 Automate releasing and publishing to npm
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-management.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  README.md
  RELEASING.md
  doczrc.js
  package-lock.json
Labels: maintenance

#162 Check for version change before attempting to publish a release draft
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/release-management.yml
  CONTRIBUTING.md
  README.md
  RELEASING.md
Labels: maintenance, skip changelog

#165 Make `auto` and `limited` label widths of horizontal `FormLayout` work in all browsers (#135)
  src/lib/components/layout/FormLayout/FormLayout.jsx
  src/lib/components/layout/FormLayout/FormLayout.scss
  src/lib/components/layout/FormLayout/FormLayoutCustomField.jsx
  src/lib/components/layout/FormLayout/FormLayoutCustomField.scss
  src/lib/components/layout/FormLayout/README.mdx
  src/lib/components/layout/FormLayout/__tests__/FormLayout.test.jsx
  src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
  src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayoutCustomField.test.jsx.snap
  src/lib/styles/settings/_forms-theme.scss
  src/lib/styles/tools/_forms.deprecated.scss
  src/lib/styles/tools/forms/_foundation.scss
  src/lib/styles/tools/forms/_layouts.scss
  src/lib/theme.scss
Labels: refactoring

#167 Introduce `autoWidth` option of `FormLayout`
  src/lib/components/layout/FormLayout/FormLayout.jsx
  src/lib/components/layout/FormLayout/FormLayout.scss
  src/lib/components/layout/FormLayout/README.mdx
  src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
  src/lib/components/layout/Toolbar/README.mdx
  src/lib/components/ui/Card/Card.scss
  src/lib/components/ui/Card/README.mdx
Labels: feature

#168 Track docs visits with Google Analytics (#166)
  .github/pr-labeler.yml
  CONTRIBUTING.md
  src/gatsby-theme-docz/wrapper.js
Labels: documentation, skip changelog

#169 Fix Release Drafter
  .github/workflows/release-management.yml
Labels: maintenance, skip changelog

#171 Fix Release Drafter
  .github/workflows/release-management.yml
Labels: maintenance, skip changelog

#177 Exclude generated docs and tests from npm bundle
  .github/workflows/release-management.yml
  .gitignore
  .npmignore
  doczrc.js
  package.json
  src/lib/components/ui/Alert/__tests__/Alert.test.jsx
  src/lib/components/ui/Alert/__tests__/__snapshots__/Alert.test.jsx.snap
  src/lib/components/ui/Badge/__tests__/Badge.test.jsx
  src/lib/components/ui/Badge/__tests__/__snapshots__/Badge.test.jsx.snap
  src/lib/components/ui/Button/__tests__/Button.test.jsx
  src/lib/components/ui/Button/__tests__/__snapshots__/Button.test.jsx.snap
  src/lib/components/ui/ButtonGroup/__tests__/ButtonGroup.test.jsx
  src/lib/components/ui/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
  src/lib/components/ui/Card/__tests__/Card.test.jsx
  src/lib/components/ui/Card/__tests__/CardBody.test.jsx
  src/lib/components/ui/Card/__tests__/CardFooter.test.jsx
  src/lib/components/ui/Card/__tests__/__snapshots__/Card.test.jsx.snap
  src/lib/components/ui/Card/__tests__/__snapshots__/CardBody.test.jsx.snap
  src/lib/components/ui/Card/__tests__/__snapshots__/CardFooter.test.jsx.snap
  src/lib/components/ui/CheckboxField/__tests__/CheckboxField.test.jsx
  src/lib/components/ui/CheckboxField/__tests__/__snapshots__/CheckboxField.test.jsx.snap
  src/lib/components/ui/Radio/__tests__/Radio.test.jsx
  src/lib/components/ui/Radio/__tests__/__snapshots__/Radio.test.jsx.snap
  src/lib/components/ui/SelectField/__tests__/SelectField.test.jsx
  src/lib/components/ui/SelectField/__tests__/__snapshots__/SelectField.test.jsx.snap
  src/lib/components/ui/TextArea/__tests__/TextArea.test.jsx
  src/lib/components/ui/TextArea/__tests__/__snapshots__/TextArea.test.jsx.snap
  src/lib/components/ui/Toggle/__tests__/Toggle.test.jsx
  src/lib/components/ui/Toggle/__tests__/__snapshots__/Toggle.test.jsx.snap
Labels: bugfix

#176 Add fullscreen size option to Modal (#175)
  src/lib/components/ui/Modal/Modal.jsx
  src/lib/components/ui/Modal/Modal.scss
  src/lib/components/ui/Modal/README.mdx
  src/lib/components/ui/Modal/_theme.scss
  src/lib/theme.scss
Labels: feature

#182 Allow wrapping of `Button` labels (#181)
  src/lib/components/ui/Button/_mixins.scss
Labels: feature
