Repository react-ui-org/react-ui, pull requests merged in 2021-03, with the labels that each got.

#239 Get rid of unwanted spacing of inline elements placed in `Toolbar`
  src/lib/components/layout/Toolbar/Toolbar.scss
Labels: bugfix

#242 Define minimum tap target size for interactive elements (#234)
  src/docs/customize/theming/forms.mdx
  src/docs/foundation/accessibility.mdx
  src/lib/components/ui/Alert/Alert.scss
  src/lib/components/ui/Alert/README.mdx
  src/lib/components/ui/CheckboxField/CheckboxField.scss
  src/lib/components/ui/Modal/Modal.scss
  src/lib/components/ui/Radio/Radio.scss
  src/lib/components/ui/ScrollView/ScrollView.scss
  src/lib/components/ui/Toggle/Toggle.scss
  src/lib/styles/theme/_accessibility.scss
  src/lib/styles/theme/_form-fields.scss
  src/lib/styles/tools/_accessibility.scss
  src/lib/styles/tools/form-fields/_box-field-layout.scss
  src/lib/styles/tools/form-fields/_inline-field-elements.scss
  src/lib/theme.scss
  webpack.config.js
Labels: feature

#246 Bring back docs `Playground` resize bar and editor max. height, both lost after theme switch
  doczrc.js
Labels: documentation

#247 Upgrade GitHub actions: setup-node and upload/download-artifact
  .github/workflows/git.yml
  .github/workflows/pull-request-meta.yml
  .github/workflows/release-management.yml
  .github/workflows/test.yml
Labels: maintenance

#245 Create `FileInputField` component (#219)
  src/lib/components/ui/FileInputField/FileInputField.jsx
  src/lib/components/ui/FileInputField/FileInputField.scss
  src/lib/components/ui/FileInputField/README.mdx
  src/lib/components/ui/FileInputField/__tests__/FileInputField.test.jsx
  src/lib/components/ui/FileInputField/__tests__/__snapshots__/FileInputField.test.jsx.snap
  src/lib/components/ui/FileInputField/index.js
  src/lib/components/ui/TextArea/README.mdx
  src/lib/components/ui/TextField/README.mdx
  src/lib/index.js
  src/lib/styles/theme/_accessibility.scss
  src/lib/styles/tools/_accessibility.scss
  webpack.config.js
Labels: feature

#248 Bump version to v0.39.0
  package-lock.json
  package.json
Labels: skip changelog

#250 Fix `CheckboxField` and `Toggle` breaking vertical `FormLayout` (#249)
  src/lib/components/layout/FormLayout/README.mdx
  src/lib/components/ui/CheckboxField/CheckboxField.jsx
  src/lib/components/ui/CheckboxField/__tests__/__snapshots__/CheckboxField.test.jsx.snap
  src/lib/components/ui/Radio/Radio.jsx
  src/lib/components/ui/Toggle/Toggle.jsx
  src/lib/components/ui/Toggle/__tests__/__snapshots__/Toggle.test.jsx.snap
  src/lib/styles/tools/form-fields/_inline-field-layout.scss
Labels: bugfix

#253 Restrict scrolling of `ScrollView` to single direction at a time (#233)
  src/lib/components/ui/ScrollView/README.mdx
  src/lib/components/ui/ScrollView/ScrollView.scss
Labels: bugfix

#251 Omit insignificant attributes from enzyme snapshots
  src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
  src/lib/components/layout/Toolbar/__tests__/__snapshots__/Toolbar.test.jsx.snap
  tests/setupEnzyme.js
Labels: maintenance

#254 Allow running jest in a discrete npm script
  package.json
Labels: maintenance

#258 Drop automatic spacing of standalone form fields (#94)
  src/lib/components/ui/CheckboxField/CheckboxField.scss
  src/lib/components/ui/FileInputField/FileInputField.scss
  src/lib/components/ui/Radio/Radio.scss
  src/lib/components/ui/SelectField/SelectField.scss
  src/lib/components/ui/TextArea/TextArea.scss
  src/lib/components/ui/TextField/TextField.scss
  src/lib/components/ui/Toggle/Toggle.scss
  src/lib/styles/tools/form-fields/_box-field-layout.scss
  src/lib/styles/tools/form-fields/_inline-field-layout.scss
  src/lib/styles/tools/form-fields/_relationships.scss
Labels: BC
