Repository react-ui-org/react-ui, pull requests merged in 2021-08, with the labels that each got.

#291 Introduce `Tabs` component (#288)
  doczrc.js
  src/docs/_components/Icon/Icon.jsx
  src/lib/components/layout/List/List.scss
  src/lib/components/ui/Tabs/README.mdx
  src/lib/components/ui/Tabs/Tabs.jsx
  src/lib/components/ui/Tabs/Tabs.scss
  src/lib/components/ui/Tabs/TabsItem.jsx
  src/lib/components/ui/Tabs/TabsItem.scss
  src/lib/components/ui/Tabs/__tests__/Tabs.test.jsx
  src/lib/components/ui/Tabs/__tests__/TabsItem.test.jsx
  src/lib/components/ui/Tabs/__tests__/__snapshots__/Tabs.test.jsx.snap
  src/lib/components/ui/Tabs/__tests__/__snapshots__/TabsItem.test.jsx.snap
  src/lib/components/ui/Tabs/_theme.scss
  src/lib/components/ui/Tabs/index.js
  src/lib/index.js
  src/lib/styles/tools/_reset.scss
  src/lib/styles/tools/_transition.scss
  src/lib/theme.scss
Labels: feature

#292 Reduce CI test runs as they are already triggered on every push to the PR branch
  .github/workflows/test.yml
Labels: maintenance

#293 Remove flex layout from `Paper` as it prevented margin collapsing of its content
  src/lib/components/ui/Card/Card.scss
  src/lib/components/ui/Paper/Paper.scss
Labels: bugfix

#294 Claim support for controlled components only
  src/docs/getting-started/usage.mdx
Labels: documentation

#296 Warn about known `Toolbar` limitations in docs
  src/lib/components/layout/Toolbar/README.mdx
Labels: documentation

#295 Re-introduce custom input size for numeric inputs (#281)
  src/lib/components/ui/TextField/README.mdx
  src/lib/components/ui/TextField/TextField.jsx
  src/lib/components/ui/TextField/TextField.scss
  src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
  src/lib/styles/settings/_form-fields.scss
  src/lib/styles/tools/form-fields/_box-field-elements.scss
Labels: feature

#297 Bump version to v0.42.0
  package-lock.json
  package.json
Labels: skip changelog

#299 Update dependencies
  package-lock.json
  package.json
Labels: maintenance, dependencies

#300 Bump version to v0.42.1
  package-lock.json
  package.json
Labels: skip changelog
