Repository react-ui-org/react-ui, pull requests merged in 2021-06, with the labels that each got.

#280 Drop support for automatically setting `TextField` size attribute based on the value of the `max` attribute for when `type=number`
  src/lib/components/ui/TextField/README.mdx
  src/lib/components/ui/TextField/TextField.jsx
  src/lib/components/ui/TextField/__tests__/TextField.test.jsx
  src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
  src/lib/components/ui/TextField/helpers/__tests__/getCustomInputSizeByType.test.js
  src/lib/components/ui/TextField/helpers/getCustomInputSizeByType.js
Labels: BC

#279 Update dependencies
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/lib/components/ui/Badge/Badge.scss
  src/lib/components/ui/Button/_tools.scss
Labels: dependencies, maintenance

#282 Make `id` optional in all components
  package-lock.json
  package.json
  src/lib/components/layout/FormLayout/README.mdx
  src/lib/components/layout/Toolbar/README.mdx
  src/lib/components/ui/CheckboxField/CheckboxField.jsx
  src/lib/components/ui/CheckboxField/README.mdx
  src/lib/components/ui/CheckboxField/__tests__/CheckboxField.test.jsx
  src/lib/components/ui/CheckboxField/__tests__/__snapshots__/CheckboxField.test.jsx.snap
  src/lib/components/ui/FileInputField/FileInputField.jsx
  src/lib/components/ui/FileInputField/README.mdx
  src/lib/components/ui/FileInputField/__tests__/FileInputField.test.jsx
  src/lib/components/ui/FileInputField/__tests__/__snapshots__/FileInputField.test.jsx.snap
  src/lib/components/ui/Radio/README.mdx
  src/lib/components/ui/Radio/Radio.jsx
  src/lib/components/ui/Radio/__tests__/Radio.test.jsx
  src/lib/components/ui/Radio/__tests__/__snapshots__/Radio.test.jsx.snap
  src/lib/components/ui/ScrollView/README.mdx
  src/lib/components/ui/SelectField/README.mdx
  src/lib/components/ui/SelectField/SelectField.jsx
  src/lib/components/ui/SelectField/__tests__/SelectField.test.jsx
  src/lib/components/ui/SelectField/__tests__/__snapshots__/SelectField.test.jsx.snap
  src/lib/components/ui/TextArea/README.mdx
  src/lib/components/ui/TextArea/TextArea.jsx
  src/lib/components/ui/TextArea/__tests__/TextArea.test.jsx
  src/lib/components/ui/TextArea/__tests__/__snapshots__/TextArea.test.jsx.snap
  src/lib/components/ui/TextField/README.mdx
  src/lib/components/ui/TextField/TextField.jsx
  src/lib/components/ui/TextField/__tests__/TextField.test.jsx
  src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
  src/lib/components/ui/Toggle/README.mdx
  src/lib/components/ui/Toggle/Toggle.jsx
  src/lib/components/ui/Toggle/__tests__/Toggle.test.jsx
  src/lib/components/ui/Toggle/__tests__/__snapshots__/Toggle.test.jsx.snap
Labels: feature

#283 Introduce `Paper` component as a primary option to hold larger content areas
  src/lib/components/ui/Card/README.mdx
  src/lib/components/ui/Paper/Paper.jsx
  src/lib/components/ui/Paper/Paper.scss
  src/lib/components/ui/Paper/README.mdx
  src/lib/components/ui/Paper/__tests__/Paper.test.jsx
  src/lib/components/ui/Paper/__tests__/__snapshots__/Paper.test.jsx.snap
  src/lib/components/ui/Paper/_theme.scss
  src/lib/components/ui/Paper/index.js
  src/lib/index.js
  src/lib/theme.scss
Labels: feature

#284 Update Stylelint configs and fix coding style
  package-lock.json
  package.json
  src/lib/components/layout/Grid/Grid.scss
  src/lib/components/ui/Button/_tools.scss
  src/lib/components/ui/Card/Card.scss
  src/lib/components/ui/ScrollView/ScrollView.scss
  src/lib/components/ui/Table/Table.scss
  src/lib/styles/tools/_reset.scss
  src/lib/styles/tools/form-fields/_box-field-elements.scss
  src/lib/styles/tools/form-fields/_inline-field-elements.scss
  src/lib/styles/tools/form-fields/_inline-field-layout.scss
  src/lib/theme.scss
Labels: maintenance

#287 Modernize Sass syntax with native Sass modules
  src/docs/_components/Placeholder/Placeholder.scss
  src/lib/components/layout/Grid/Grid.scss
  src/lib/components/layout/Grid/_tools.scss
  src/lib/components/ui/Alert/Alert.scss
  src/lib/components/ui/Alert/_settings.scss
  src/lib/components/ui/Alert/_tools.scss
  src/lib/components/ui/Badge/Badge.scss
  src/lib/components/ui/Button/_base.scss
  src/lib/components/ui/Button/_priorities.scss
  src/lib/components/ui/Button/_tools.scss
  src/lib/components/ui/Card/_tools.scss
  src/lib/components/ui/Modal/Modal.scss
  src/lib/components/ui/Modal/_settings.scss
  src/lib/components/ui/Table/_settings.scss
  src/lib/styles/_utilities.scss
  src/lib/styles/elements/_code.scss
  src/lib/styles/elements/_rulers.scss
  src/lib/styles/settings/_form-fields.scss
  src/lib/styles/settings/_utilities.scss
  src/lib/styles/theme-constants/_breakpoints.scss
  src/lib/styles/theme-constants/_colors.scss
  src/lib/styles/tools/_breakpoint.scss
  src/lib/styles/tools/_colors.scss
  src/lib/styles/tools/_spacing.scss
  src/lib/styles/tools/_string.scss
  src/lib/styles/tools/_svg.scss
  src/lib/styles/tools/_transition.scss
  src/lib/styles/tools/_utilities.scss
  src/lib/styles/tools/form-fields/_box-field-sizes.scss
  src/lib/styles/tools/form-fields/_variants.scss
Labels: refactoring

#289 Introduce `Text` component to control wrapping of text content (#286)
  src/docs/_components/Placeholder/Placeholder.jsx
  src/docs/_components/Placeholder/Placeholder.scss
  src/lib/components/layout/Toolbar/README.mdx
  src/lib/components/ui/Text/README.mdx
  src/lib/components/ui/Text/Text.jsx
  src/lib/components/ui/Text/Text.scss
  src/lib/components/ui/Text/__tests__/Text.test.jsx
  src/lib/components/ui/Text/__tests__/__snapshots__/Text.test.jsx.snap
  src/lib/components/ui/Text/helpers/getRootHyphensClassName.js
  src/lib/components/ui/Text/helpers/getRootWordWrappingClassName.js
  src/lib/components/ui/Text/index.js
  src/lib/index.js
Labels: feature
