Repository react-ui-org/react-ui, pull requests merged in 2021-02, with the labels that each got.

#220 Separate theme related Sass variables from other settings
  src/docs/_components/Placeholder/Placeholder.scss
  src/lib/components/layout/FormLayout/FormLayout.scss
  src/lib/components/ui/Alert/Alert.scss
  src/lib/components/ui/Alert/_settings.scss
  src/lib/components/ui/Badge/Badge.scss
  src/lib/components/ui/Button/_settings.scss
  src/lib/components/ui/CheckboxField/CheckboxField.scss
  src/lib/components/ui/Modal/Modal.scss
  src/lib/components/ui/Modal/_settings.scss
  src/lib/components/ui/Table/_settings.scss
  src/lib/components/ui/Toggle/Toggle.scss
  src/lib/styles/elements/_code.scss
  src/lib/styles/elements/_links.scss
  src/lib/styles/elements/_lists.scss
  src/lib/styles/elements/_page.scss
  src/lib/styles/elements/_rulers.scss
  src/lib/styles/elements/_small.scss
  src/lib/styles/settings/_forms.deprecated.scss
  src/lib/styles/settings/_forms.scss
  src/lib/styles/settings/_utilities.scss
  src/lib/styles/theme/_borders.scss
  src/lib/styles/theme/_colors.scss
  src/lib/styles/theme/_forms.scss
  src/lib/styles/theme/_links.scss
  src/lib/styles/theme/_lists.scss
  src/lib/styles/theme/_page.scss
  src/lib/styles/theme/_spacing.scss
  src/lib/styles/theme/_typography.scss
  src/lib/styles/tools/_forms.deprecated.scss
  src/lib/styles/tools/_spacing.scss
  src/lib/styles/tools/forms/_foundation.scss
  src/lib/styles/tools/forms/_layouts.scss
  src/lib/styles/tools/forms/_sizes.scss
  src/lib/styles/tools/forms/_variants.scss
Labels: refactoring

#221 Make code font family and font size customizable
  doczrc.js
  src/gatsby-theme-docz/index.css
  src/gatsby-theme-docz/theme/prism/dark.js
  src/gatsby-theme-docz/theme/prism/light.js
  src/lib/styles/elements/_code.scss
  src/lib/styles/theme/_code.scss
  src/lib/theme.scss
Labels: feature

#222 Collapse Playground code by default
  doczrc.js
Labels: documentation

#223 Bump version to v0.37.0
  package-lock.json
  package.json
Labels: skip changelog

#230 Change UI component exports to fix `withForwardedRef` (#229)
  src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
  src/lib/components/ui/Button/Button.jsx
  src/lib/components/ui/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
  src/lib/components/ui/CheckboxField/CheckboxField.jsx
  src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/lib/components/ui/SelectField/SelectField.jsx
  src/lib/components/ui/Table/__tests__/__snapshots__/Table.test.jsx.snap
  src/lib/components/ui/TextArea/TextArea.jsx
  src/lib/components/ui/TextField/TextField.jsx
  src/lib/components/ui/Toggle/Toggle.jsx
  src/lib/provider/__tests__/__snapshots__/RUIProvider.test.jsx.snap
Labels: bugfix

#228 Update dependencies (#227)
  gatsby-config.js
  package-lock.json
  package.json
Labels: dependencies, maintenance

#231 Bump version to v0.38.0
  package-lock.json
  package.json
Labels: skip changelog
