Repository react-ui-org/react-ui, pull requests merged in 2021-04, with the labels that each got.

#260 Use unitless line height to take advantage of inheritance
  src/lib/styles/tools/form-fields/_box-field-layout.scss
  src/lib/styles/tools/form-fields/_inline-field-elements.scss
  src/lib/theme.scss
Labels: BC

#259 Remove bottom margin from last-child elements (#180)
  src/docs/foundation/spacing.mdx
  src/lib/components/layout/CTA/CTA.scss
  src/lib/components/layout/FormLayout/FormLayout.scss
  src/lib/components/layout/FormLayout/README.mdx
  src/lib/components/layout/Grid/Grid.scss
  src/lib/components/layout/List/List.scss
  src/lib/components/layout/Media/Media.scss
  src/lib/components/layout/Toolbar/README.mdx
  src/lib/components/layout/Toolbar/Toolbar.scss
  src/lib/components/ui/Modal/Modal.scss
  src/lib/components/ui/Modal/_settings.scss
  src/lib/components/ui/ScrollView/README.mdx
  src/lib/styles/generic/_shared.scss
  src/lib/styles/settings/_layouts.scss
  src/lib/styles/theme/_spacing.scss
  src/lib/styles/tools/_spacing.scss
  src/lib/theme.scss
Labels: BC

#262 Update dependencies (#261)
  .eslintrc
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies, maintenance

#267 Bump version to v0.40.0
  package-lock.json
  package.json
Labels: skip changelog
