Repository react-ui-org/react-ui, pull requests merged in 2022-08, with the labels that each got.

#396 Rewrite `ScrollView` API to limit the number of customization approaches (#303)
  src/lib/components/ScrollView/README.mdx
  src/lib/components/ScrollView/ScrollView.jsx
  src/lib/components/ScrollView/ScrollView.scss
  src/lib/components/ScrollView/__tests__/ScrollView.test.jsx
  src/lib/components/ScrollView/_theme.scss
  src/lib/theme.scss
Labels: BC

#398 Document pitfalls of combining horizontal `FormLayout` with small `Modal` (#386)
  src/lib/components/Modal/README.mdx
Labels: documentation

#399 Do not let auto-sized `Modal` overflow the viewport when min/max limits are too large
  src/lib/components/Modal/Modal.scss
  src/lib/components/Modal/README.mdx
Labels: bug

#400 Update supported browser versions
  package-lock.json
Labels: maintenance

#407 Limit `Grid` gap props to accept only available spacing values (#402)
  src/docs/contribute/api.mdx
  src/lib/components/Grid/Grid.jsx
  src/lib/components/Grid/README.mdx
  src/lib/components/Grid/__tests__/Grid.test.jsx
  src/lib/components/Grid/_helpers/__tests__/generateResponsiveCustomProperties.test.js
  src/lib/components/Grid/_helpers/generateResponsiveCustomProperties.js
Labels: BC

#409 Bump version to v0.48.0
  package-lock.json
  package.json
Labels: skip changelog

#408 Add support for ref forwarding in ScrollView (#406)
  src/lib/components/ScrollView/ScrollView.jsx
  src/lib/components/ScrollView/__tests__/ScrollView.test.jsx
Labels: feature
