Repository react-ui-org/react-ui, pull requests merged in 2022-04, with the labels that each got.

#370 Fix truncating of single-line `Text` broken in some scenarios #334
  src/lib/components/Text/README.mdx
  src/lib/components/Text/Text.jsx
  src/lib/components/Text/Text.scss
  src/lib/components/Text/__tests__/Text.test.jsx
  src/lib/components/Text/_helpers/getRootClampClassName.js
Labels: bug

#371 Require Node 16 which is current LTS
  .github/workflows/git.yml
  .github/workflows/pull-request-meta.yml
  .github/workflows/release-management.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: BC

#372 Update GitHub actions to their latest versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/git.yml
  .github/workflows/pull-request-meta.yml
  .github/workflows/release-management.yml
  .github/workflows/test.yml
Labels: maintenance

#368 Rename `Link` component to `TextLink` and pass in the display value via `label` prop instead of `children`
  src/lib/components/Button/README.mdx
  src/lib/components/CheckboxField/README.mdx
  src/lib/components/FileInputField/README.mdx
  src/lib/components/Link/Link.scss
  src/lib/components/Link/README.mdx
  src/lib/components/Link/_theme.scss
  src/lib/components/Link/index.js
  src/lib/components/Radio/README.mdx
  src/lib/components/SelectField/README.mdx
  src/lib/components/TextArea/README.mdx
  src/lib/components/TextField/README.mdx
  src/lib/components/TextLink/README.mdx
  src/lib/components/TextLink/TextLink.jsx
  src/lib/components/TextLink/TextLink.scss
  src/lib/components/TextLink/__tests__/Link.test.jsx
  src/lib/components/TextLink/_theme.scss
  src/lib/components/TextLink/index.js
  src/lib/components/Toggle/README.mdx
  src/lib/index.js
  src/lib/theme.scss
Labels: BC
