Repository react-ui-org/react-ui, pull requests merged in 2022-01, with the labels that each got.

#355 Vertically expand `Button`s with long labels to prevent overflow
  src/docs/foundation/typography.mdx
  src/lib/components/Alert/_settings.scss
  src/lib/components/Button/README.mdx
  src/lib/components/Button/_settings.scss
  src/lib/components/Button/_theme.scss
  src/lib/components/Button/_tools.scss
  src/lib/styles/theme/_typography.scss
  src/lib/theme.scss
Labels: feature

#356 Link sizes of box form fields to `Button` sizes to make customisation easier
  src/docs/customize/theming/forms.mdx
  src/lib/components/Button/README.mdx
  src/lib/theme.scss
Labels: feature

#359 Minor update of CSS dev dependencies
  package-lock.json
  package.json
Labels: dependencies

#342 Refactor components which use multiple class names to use `classNames` util to unify approach of writing class names and to avoid empty spaces in output; refactor all helper files to use named exports, move all helper files from `services` and `utils` into `helpers` folder and rename all `helpers` folders on component level to `_helpers` (#270)
  doczrc.js
  src/docs/_components/Placeholder/Placeholder.jsx
  src/docs/js-helpers/classnames.mdx
  src/lib/components/Alert/Alert.jsx
  src/lib/components/Badge/Badge.jsx
  src/lib/components/Button/Button.jsx
  src/lib/components/ButtonGroup/ButtonGroup.jsx
  src/lib/components/CTA/CTA.jsx
  src/lib/components/Card/Card.jsx
  src/lib/components/CheckboxField/CheckboxField.jsx
  src/lib/components/FileInputField/FileInputField.jsx
  src/lib/components/FormLayout/FormLayout.jsx
  src/lib/components/FormLayout/FormLayoutCustomField.jsx
  src/lib/components/Grid/Grid.jsx
  src/lib/components/Grid/GridSpan.jsx
  src/lib/components/Grid/_helpers/__tests__/generateResponsiveCustomProperties.test.js
  src/lib/components/Grid/_helpers/generateResponsiveCustomProperties.js
  src/lib/components/Link/Link.jsx
  src/lib/components/List/List.jsx
  src/lib/components/Modal/Modal.jsx
  src/lib/components/Paper/Paper.jsx
  src/lib/components/Radio/Radio.jsx
  src/lib/components/ScrollView/ScrollView.jsx
  src/lib/components/ScrollView/_helpers/getElementsPositionDifference.js
  src/lib/components/ScrollView/_hooks/useLoadResizeHook.js
  src/lib/components/ScrollView/_hooks/useScrollPositionHook.js
  src/lib/components/SelectField/SelectField.jsx
  src/lib/components/Tabs/TabsItem.jsx
  src/lib/components/Text/Text.jsx
  src/lib/components/Text/_helpers/getRootHyphensClassName.js
  src/lib/components/Text/_helpers/getRootWordWrappingClassName.js
  src/lib/components/TextArea/TextArea.jsx
  src/lib/components/TextField/TextField.jsx
  src/lib/components/Toggle/Toggle.jsx
  src/lib/components/Toolbar/Toolbar.jsx
  src/lib/components/Toolbar/ToolbarGroup.jsx
  src/lib/components/_helpers/__tests__/transferProps.test.js
  src/lib/components/_helpers/getRootColorClassName.js
  src/lib/components/_helpers/getRootSizeClassName.js
  src/lib/components/_helpers/getRootValidationStateClassName.js
  src/lib/components/_helpers/resolveContextOrProp.js
  src/lib/components/_helpers/transferProps.js
  src/lib/index.js
  src/lib/utils/__tests__/classNames.js
  src/lib/utils/classNames.js
Labels: refactoring

#362 Extend box alignment helper classes to cover more use cases with `Grid` and flex helper
  src/docs/css-helpers/box-alignment.mdx
  src/lib/styles/settings/_utilities.scss
Labels: feature

#363 Drop rarely used `CTA` and `Center` components in favour of `Grid` and helper classes (#361)
  src/lib/components/CTA/CTA.jsx
  src/lib/components/CTA/CTA.scss
  src/lib/components/CTA/CTACenter.jsx
  src/lib/components/CTA/CTAEnd.jsx
  src/lib/components/CTA/CTAStart.jsx
  src/lib/components/CTA/README.mdx
  src/lib/components/CTA/__tests__/CTA.test.jsx
  src/lib/components/CTA/__tests__/CTACenter.test.jsx
  src/lib/components/CTA/__tests__/CTAEnd.test.jsx
  src/lib/components/CTA/__tests__/CTAStart.test.jsx
  src/lib/components/CTA/index.js
  src/lib/components/Center/Center.jsx
  src/lib/components/Center/Center.scss
  src/lib/components/Center/README.mdx
  src/lib/components/Center/__tests__/Center.test.jsx
  src/lib/components/Center/index.js
  src/lib/components/FormLayout/README.mdx
  src/lib/index.js
Labels: BC, feature drop

#364 Bump version to v0.45.0
  package-lock.json
  package.json
Labels: skip changelog
