Repository react-ui-org/react-ui, pull requests merged in 2023-10, with the labels that each got.

#500 Release v0.52.1
  package-lock.json
  package.json
Labels: skip changelog

#497 Define strategy how to transfer HTML attributes to the component and accordingly modify the `TabsItem` component
  CONTRIBUTING.md
  src/components/Tabs/README.md
  src/components/Tabs/TabsItem.jsx
Labels: feature

#502 Move `transferProps` back from `fieldset` to `input` in `RadioField` (#481)
  src/components/Radio/README.md
  src/components/Radio/Radio.jsx
Labels: feature

#504 Fix `Modal` previews being overlapped by MkDocs header (#471)
  src/docs/_overrides/main.html
Labels: documentation

#507 Intentionally omit patch version in Prism CSS URL due to parsing bug in Safari (#506)
  src/docs/_assets/stylesheets/extra.css
Labels: bug
