Repository react-ui-org/react-ui, pull requests merged in 2023-09, with the labels that each got.

#485 Fix navigation hierarchy
  mkdocs.yml
Labels: bug

#476 Narrow down supported browsers in Browserslist config according to the docs
  .browserslistrc
  package-lock.json
Labels: maintenance

#479 Introduce `CODEOWNERS` file to define responsibility for code in the repository
  CODEOWNERS
Labels: maintenance

#482 Allow the `Modal` component to block scrolling on any HTML element instead of just the `<body>` element (#472)
  src/components/Modal/Modal.jsx
  src/components/Modal/README.md
  src/components/Modal/_hooks/useModalScrollPrevention.js
Labels: feature

#490 Rename CSS and JS endpoints to use hyphenation
  .npmignore
  package.json
  src/docs/_assets/stylesheets/extra.css
  src/docs/_overrides/main.html
  src/docsCustomProperties.js
  webpack.config.babel.js
Labels: refactoring, skip changelog

#491 Update Usage instructions according to the current state of things (#197)
  src/docs/getting-started/usage.md
Labels: documentation

#495 Remove invisible `InputGroup` and `Radio` labels from code since parent `<fieldset>`s still have accessible `<legend>`
  src/components/InputGroup/InputGroup.jsx
  src/components/InputGroup/InputGroup.scss
  src/components/Radio/Radio.jsx
  src/components/Radio/Radio.scss
  tests/propTests/isLabelVisibleTest.js
Labels: BC
