Repository react-ui-org/react-ui, pull requests merged in 2024-09, with the labels that each got.

#564 Include `refactor/*` branch name for the `refactoring` label
  .github/pr-labeler.yml
Labels: maintenance

#561 Make `Badge` priority class always present like in all other components
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.module.scss
  src/components/Badge/__tests__/Badge.test.jsx
  src/components/Button/Button.jsx
  src/components/ButtonGroup/ButtonGroup.jsx
  src/components/_helpers/getRootPriorityClassName.js
Labels: BC

#559 Fix rendering glitch of `Popover` arrow on low-dpi displays
  src/components/Popover/Popover.module.scss
  src/components/Popover/_theme.scss
  webpack.config.babel.js
Labels: fix
