Repository react-ui-org/react-ui, pull requests merged in 2024-03, with the labels that each got.

#527 Prevent `Tabs` and `ScrollView` from unwanted cross-axis scrolling during keyboard navigation #499
  src/components/ScrollView/ScrollView.scss
  src/components/Tabs/Tabs.scss
Labels: bug

#528 Correct the documentation of CSS usage
  README.md
  src/docs/getting-started/usage.md
  src/index.js
Labels: documentation

#520 Update blacklisted props that can be passed to native HTML elements using the transferProps principle
  src/components/_helpers/__tests__/transferProps.test.js
  src/components/_helpers/transferProps.js
Labels: feature

#530 Bump version to v0.55.0
  package-lock.json
  package.json
Labels: skip changelog
