Repository react-ui-org/react-ui, pull requests merged in 2025-07, with the labels that each got.

#653 Fix modal closing when selection ended outside of the modal (#645)
  src/components/Modal/Modal.jsx
  src/components/Modal/_helpers/dialogOnClickHandler.js
Labels: fix

#658 Add text when the user is dragging files over FileInputField
  src/components/FileInputField/FileInputField.jsx
  src/components/FileInputField/FileInputField.module.scss
  src/translations/en.js
Labels: feature

#656 Add custom properties for the border of disabled cards
  src/components/Card/Card.module.scss
  src/components/Card/README.md
  src/components/Card/_theme.scss
  src/theme.scss
Labels: feature

#657 Fix `ScrollView` scroll position issues (#501)
  src/components/ScrollView/ScrollView.jsx
  src/components/ScrollView/_hooks/useScrollPositionHook.js
Labels: fix

#660 Bump version to v0.60.0
  package-lock.json
  package.json
Labels: skip changelog
