Repository react-ui-org/react-ui, pull requests merged in 2025-06, with the labels that each got.

#652 Bump version to v0.59.3
  package-lock.json
  package.json
Labels: skip changelog

#637 Transform FileInputField jest tests into playwright. (#603)
  src/components/FileInputField/__tests__/FileInputField.spec.tsx
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-defaultComponentProps-object-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-false-validationState-string-invalid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-false-validationState-string-valid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-false-validationState-string-warning-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-false-validationState-undefined-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-true-validationState-string-invalid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-true-validationState-string-valid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-true-validationState-string-warning-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-disabled-boolean-true-validationState-undefined-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-filledInputField-object-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-filledInputField-object-validationState-string-invalid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-filledInputField-object-validationState-string-valid-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-filledInputField-object-validationState-string-warning-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-filledInputField-object-validationState-undefined-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-fullWidth-boolean-false-layout-string-horizontal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-fullWidth-boolean-false-layout-string-vertical-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-fullWidth-boolean-true-layout-string-horizontal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-fullWidth-boolean-true-layout-string-vertical-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-node-normal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-string-long-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-string-normal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-string-validationText-string-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-string-validationText-undefined-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-helpText-undefined-validationText-string-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-isLabelVisible-boolean-false-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-isLabelVisible-boolean-true-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-label-node-normal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-label-string-long-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-required-boolean-false-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-required-boolean-true-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-size-string-large-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-size-string-medium-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-size-string-small-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-validationText-node-normal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-validationText-string-long-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-base-visual-validationText-string-normal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-formLayout-visual-layout-string-horizontal-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.spec.tsx-snapshots/FileInputField-formLayout-visual-layout-string-vertical-1-chromium-linux.png
  src/components/FileInputField/__tests__/FileInputField.story.tsx
  src/components/FileInputField/__tests__/FileInputField.test.jsx
  src/components/FileInputField/__tests__/_propTests/fileSelectedPropTest.ts
  src/components/TextField/__tests__/TextField.spec.tsx
Labels: refactoring, testing

#640 Transform popup from jest to playwright (#597)
  src/components/Popover/__tests__/Popover.spec.tsx
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-defaultComponentProps-object-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-opoverTargetId-shape-open-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-bottom-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-bottom-end-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-bottom-start-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-left-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-left-end-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-left-start-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-right-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-right-end-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-right-start-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-top-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-top-end-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-placement-enum-top-start-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.spec.tsx-snapshots/Popover-visual-popoverTargetId-shape-closed-1-chromium-linux.png
  src/components/Popover/__tests__/Popover.story.tsx
  src/components/Popover/__tests__/Popover.test.jsx
  src/components/Popover/__tests__/PopoverWrapper.spec.tsx
  src/components/Popover/__tests__/PopoverWrapper.story.tsx
  src/components/Popover/__tests__/PopoverWrapper.test.jsx
  src/components/Popover/__tests__/_propTests/placementPropTest.ts
  src/components/Popover/__tests__/_propTests/popoverTargetIdPropTest.ts
Labels: documentation, refactoring, testing
