Repository react-ui-org/react-ui, pull requests merged in 2025-01, with the labels that each got.

#582 Add controlled popover
  src/components/Popover/Popover.jsx
  src/components/Popover/Popover.module.scss
  src/components/Popover/README.md
Labels: feature

#545 Replace `jsdom` with `happy-dom` testing environment to enable `Modal` tests (#461)
  jest.config.js
  package-lock.json
  package.json
  src/components/Grid/__tests__/Grid.test.jsx
  src/components/Modal/__tests__/Modal.test.jsx
  src/components/Modal/__tests__/ModalTitle.test.jsx
  src/components/Modal/_helpers/dialogOnKeyDownHandler.js
  src/components/Radio/__tests__/Radio.test.jsx
  tests/propTests/tagPropTest.js
Labels: BC

#583 Split `RUIProvider` into two
  src/components/Alert/Alert.jsx
  src/components/Alert/README.md
  src/components/Badge/Badge.jsx
  src/components/Button/Button.jsx
  src/components/ButtonGroup/ButtonGroup.jsx
  src/components/Card/Card.jsx
  src/components/Card/CardBody.jsx
  src/components/Card/CardFooter.jsx
  src/components/CheckboxField/CheckboxField.jsx
  src/components/FileInputField/FileInputField.jsx
  src/components/FormLayout/FormLayout.jsx
  src/components/FormLayout/FormLayoutCustomField.jsx
  src/components/Grid/Grid.jsx
  src/components/Grid/GridSpan.jsx
  src/components/InputGroup/InputGroup.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalBody.jsx
  src/components/Modal/ModalCloseButton.jsx
  src/components/Modal/ModalContent.jsx
  src/components/Modal/ModalFooter.jsx
  src/components/Modal/ModalHeader.jsx
  src/components/Modal/ModalTitle.jsx
  src/components/Modal/README.md
  src/components/Paper/Paper.jsx
  src/components/Popover/Popover.jsx
  src/components/Popover/PopoverWrapper.jsx
  src/components/Radio/Radio.jsx
  src/components/ScrollView/ScrollView.jsx
  src/components/SelectField/SelectField.jsx
  src/components/Table/Table.jsx
  src/components/Tabs/Tabs.jsx
  src/components/Tabs/TabsItem.jsx
  src/components/Text/Text.jsx
  src/components/TextArea/TextArea.jsx
  src/components/TextField/TextField.jsx
  src/components/TextLink/TextLink.jsx
  src/components/Toggle/Toggle.jsx
  src/components/Toolbar/Toolbar.jsx
  src/components/Toolbar/ToolbarGroup.jsx
  src/components/Toolbar/ToolbarItem.jsx
  src/docs/customize/global-props.md
  src/docs/customize/translations.md
  src/index.js
  src/provider/RUIContext.jsx
  src/provider/RUIProvider.jsx
  src/provider/index.js
  src/providers/globalProps/GlobalPropsContext.jsx
  src/providers/globalProps/GlobalPropsProvider.jsx
  src/providers/globalProps/__tests__/GlobalPropsProvider.test.jsx
  src/providers/globalProps/index.js
  src/providers/globalProps/withGlobalProps.jsx
  src/providers/translations/TranslationsContext.jsx
  src/providers/translations/TranslationsProvider.jsx
  src/providers/translations/__tests__/TranslationsProvider.test.jsx
  src/providers/translations/index.js
Labels: BC, refactoring, performance

#581 Allow check fields and selectable fields to render as required #487
  src/components/CheckboxField/CheckboxField.jsx
  src/components/CheckboxField/README.md
  src/components/CheckboxField/__tests__/CheckboxField.test.jsx
  src/components/Radio/README.md
  src/components/Radio/Radio.jsx
  src/components/Radio/Radio.module.scss
  src/components/Radio/__tests__/Radio.test.jsx
  src/components/SelectField/README.md
  src/components/SelectField/SelectField.jsx
  src/components/SelectField/__tests__/SelectField.test.jsx
  src/components/Toggle/README.md
  src/components/Toggle/Toggle.jsx
  src/components/Toggle/__tests__/Toggle.test.jsx
  src/docs/customize/theming/forms.md
  src/styles/tools/form-fields/_foundation.scss
  tests/propTests/renderAsRequiredPropTest.js
Labels: BC
